; ============================================================
;  NuraShade Skin
;  Copyright (c) 2025 NuraShade
;
;  Licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License.
;  You are free to:
;    • Share — copy and redistribute the material in any medium or format
;    • Adapt — remix, transform, and build upon the material
;      for any purpose, even commercially.
;
;  Under the following terms:
;    • Attribution — You must give appropriate credit, provide a link to the license,
;      and indicate if changes were made.
;    • ShareAlike — If you remix, transform, or build upon the material,
;      you must distribute your contributions under the same license as the original.
;
;  License Details: https://creativecommons.org/licenses/by-sa/3.0/
; ============================================================
[Variables]
Round_Type=Round
Primary_Color=33, 29, 37
Secondary_Color=42, 38, 48
Primary_Text_Color=230,225,240
Secondary_Text_Color=145,145,158
Border_Color=55, 51, 62
Icon_Color=230,225,240
Active_Icon_Color=190, 160, 255
On_Hover_Color=165,142,255,20
Font_Style=Inter
Skin_Name=NuraShade
Primary_Accent_Color=138, 43, 226
Secondary_Accent_Color=59, 130, 246